[package]
name = "snappy-genesis-benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snap = "1.0.1"
criterion = "0.3"

[[bench]]
name = "genesis_benchmark"
harness = false